sonar.projectKey=stylehub
sonar.projectName=StyleHub
sonar.sources=backend,frontend,styleHub_admin
sonar.host.url=http://localhost:9000
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.git/**,**/coverage/**